Feature/co 1365 edit textbook integration test
osu-mist/textbooks-api pull request #13
Opened 2019-01-23 18:23 UTC by MohammedAlawami

2019-01-23 19:03 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +                random_section = random.randint(0, len(course["sections"]) - 1)
That could work. Just wanna let you know you can also use [random.sample](https://docs.python.org/3.7/library/random.html#random.sample) to pick samples directly.

2019-01-24 18:27 UTC, ianbrown9475 requested changes

2019-01-24 18:27 UTC, ianbrown9475 commented on src/test/integration/integration_tests.py
> +    # if this line was excuted that means there was nothing found in the loop.
Minor typo

2019-01-24 18:27 UTC, ianbrown9475 commented on src/test/integration/integration_tests.py
> +    # the first valid term, course, and a random section ther is
Minor typo

2019-01-24 18:27 UTC, ianbrown9475 commented on src/test/integration/integration_tests.py
> +            # if sections is empty loop agian to find a course
Minor typo here

2019-01-28 19:02 UTC, merged